spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev                   #å¼€å‘ç¯å¢?
  application:
    name: service-config-dev
    
---
spring:
  profiles: test                  #æµ‹è¯•ç¯å¢ƒ
  application:
    name: service-config-test